# Generated by Django 2.2.24 on 2022-03-06 07:06

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_auto_20210823_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='mainColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for main color.', verbose_name='Main Color'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CurrentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CurrentTheme', to='appearance.Theme', verbose_name='CurrentTheme')),
            ],
            options={
                'verbose_name': 'CurrentTheme',
                'verbose_name_plural': 'CurrentTheme',
            },
        ),
    ]
