# Generated by Django 2.2.24 on 2022-03-06 07:14

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_auto_20220306_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='bg_Main_Menu',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for main menu background color.', verbose_name='Background color main menu.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_Main_Menu_at',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for active of main menu top bar.', verbose_name='Active color main menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_bd',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for background body.', verbose_name='Background body color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='ct_bg_color',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for background content color.', verbose_name='Content background color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='sc_bt_button',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for second button.', verbose_name='Second background button'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='sc_tx_color',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for second text.', verbose_name='Second text body color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='tx_main',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for main text.', verbose_name='Main text color'),
            preserve_default=False,
        ),
    ]
