# Generated by Django 2.2.24 on 2022-03-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0005_auto_20220306_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='mainColor',
        ),
    ]
