# Generated by Django 2.2.24 on 2022-03-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0007_auto_20220306_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='LogoImage',
            field=models.ImageField(default='testimg', help_text='Change the logo of website.', upload_to='Logo_images', verbose_name='Logo of website'),
            preserve_default=False,
        ),
    ]
