# Generated by Django 2.2.24 on 2022-03-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0008_theme_logoimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='LogoImage',
        ),
    ]
