# Generated by Django 2.2.24 on 2022-03-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0009_remove_theme_logoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='logo',
            field=models.CharField(db_index=True, default='https://i.imgur.com/MRSWq6d.png%22', help_text='Change Logo Website.', max_length=128, unique=True, verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
