# Generated by Django 2.2.24 on 2022-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0010_theme_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font',
            field=models.CharField(choices=[('Brush Script MT', 'Brush Script Mt'), ('Tahoma', 'TahomA')], db_index=True, default='IM Fell English SC', help_text='Change Font', max_length=128, unique=True, verbose_name='Font'),
            preserve_default=False,
        ),
    ]
