# Generated by Django 2.2.24 on 2022-03-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0013_auto_20220308_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='logo_file',
        ),
    ]
