# Generated by Django 2.2.24 on 2022-03-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0016_auto_20220319_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='import_file',
        ),
    ]
