# Generated by Django 2.2.24 on 2022-03-20 20:04

from django.db import migrations, models
import mayan.apps.appearance.models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0021_auto_20220319_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='label',
            field=models.CharField(db_index=True, help_text='A short text describing the theme.', max_length=128, unique=True, validators=[mayan.apps.appearance.models.validate_empty], verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logo',
            field=models.CharField(default='https://i.imgur.com/MRSWq6d.png', help_text='Change Logo Website.', max_length=300, verbose_name='Logo'),
        ),
    ]
