# Generated by Django 2.2.24 on 2022-03-07 11:29

from django.db import migrations, models
import mayan.apps.converter.models
import mayan.apps.storage.classes


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0020_auto_20220307_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(storage=mayan.apps.storage.classes.DefinedStorageLazy(name='converter__assets'), upload_to=mayan.apps.converter.models.upload_to, verbose_name='File'),
        ),
    ]
